apiVersion: v1
kind: Service
metadata:
    name: myapp-service

spec:
    type: NodePort
    port:
    - targetPort: 80
      port: 80
      NodePort: 30008
    selector:
        app: myapp
        type: front-end 