apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: myapp-replicaset
spec:
  selector:
    matchLabels:
      app: myapp
  replicas: 3
  template:
    metadata:
      name: ngnix-2
      labels:
        app: myapp
    spec:
      containers:
        - name: nginx-container
          image: nginx
